### ISSUE TITLE
Emoji Keyboard?

### ISSUE THREAD

**Issue by RunaRagnarok** [Exmaralda-Org/exmaralda#234]
Is there a possibility to integrate an emoji keyboard?
Close if stupid...

**Comment by berndmoos** [comment]
Not stupid ;-) Take one of these...

https://github.com/Exmaralda-Org/exmaralda/blob/master/src/org/exmaralda/partitureditor/unicodeKeyboard/Charsets/BrailleIntonation.xml

... and look here ...

https://unicode.org/emoji/charts/full-emoji-list.html

... select and make a new keyboard definition emojis.xml. I'm not sure what kind of font you would need for this.

**Comment by RunaRagnarok** [comment]
Can I use Arial Unicode MS as font?
In misc symbols you used size 20, this seems to work.

**Comment by berndmoos** [comment]
> Can I use Arial Unicode MS as font?

Sure, if it has the glyphs for the emojis.

**Comment by RunaRagnarok** [comment]
Arial Unicode MS has only a few Emojis. I used a pre installed font from Windows (Segoe UI Emoji) and Apple (Apple Color Emoji). On windows it is installed an on Mac it should be ;)

**Comment by berndmoos** [comment]
Looks good (on Windows), but some glyphs seem to be missing:

![image](https://user-images.githubusercontent.com/13796493/100917741-db7dcd80-34d7-11eb-89b0-6e1f18c15cec.png)

**Comment by RunaRagnarok** [comment]
This is strange, cause in Word the symbols are there and Unicode is correct in the xml, here the star-eyed thing.
Is it possible that your font isn't up to date?
<img width="434" alt="Emojis" src="https://user-images.githubusercontent.com/54099494/101040855-8942b800-357c-11eb-8edb-683a907d80a6.PNG">

**Comment by berndmoos** [comment]
> Is it possible that your font isn't up to date?

Yes that's a possibility. Do you have an idea how to update it? Do the EXMARaLDA glyphs show in the latest preview on your computer?

**Comment by RunaRagnarok** [comment]
Sadly not. Can I access the testversion? To check the unicodes of the missing glyphs and to see which one I can't see?

**Comment by RunaRagnarok** [comment]
Oh, its already there. I take a look

**Comment by RunaRagnarok** [comment]
Bei mir fehlen die gleichen Symbole wie bei dir. Im Keyboard werden sowohl die Apple als auch die Windows Symbole angezeigt, bei beiden fehlen die gleichen Zeichen. Das ist komisch, denn auf dem Windows Rechner ist die Apple Schriftart nicht installiert. Ich glaube, es wird sich nicht auf die definierten Schriftarten bezogen sondern auf etwas übergeordnetes, damit kenne ich mich aber zu wenig aus.
Hier habe ich eine (veraltete) Liste gefunden, in der genau die selben Symbole wie im Partitur-Editor verwendet werden, die Schrift nennt sich Symbola, hier fehlen auch die gleichen Symbole wie im Partitur-Editor, ich habe sie jedoch NICHT auf meinem Rechner installiert.
Kurz, ich weiß nicht woher die Symbole kommen, also habe ich die fehlenden auskommentiert (in der Windows Version). Man müsste auf dem Mac testen ob sie angezeigt werden, dann braucht man nur ein Emoji-xml, da es wohl eh nichts mit den Schriftarten zu tun hat. Falls es mit der Windows Version auf Mac nicht funktioniert ändere ich es in der Mac Version auch noch.

**Comment by RunaRagnarok** [comment]
https://apps.timwhitlock.info/emoji/tables/unicode#block-6a-additional-emoticons

**Comment by berndmoos** [comment]
The font definitely contains the glyphs. Seems like the java.awt.Font class is saying that it can't display them, but it can. Since for all keys where the font says it can't display them, the fallback is 'Arial Unicode MS', we're only seeing those glyphs which are in Arial Unicode MS. (Dirty) fix is to enforce the font if its name contains "Emoji". Did that. New preview under way.

**Comment by RunaRagnarok** [comment]
Can't install the new version: setupfiles are corrupted

**Comment by berndmoos** [comment]
Wer hat mein Setuplein korrumpiert? Try again, please...

**Comment by RunaRagnarok** [comment]
Much better now, but some are still missing. Namely these, which have no symbol in Browser column
https://www.unicode.org/emoji/charts/full-emoji-list.html
Should I comment out or take them out?

**Comment by berndmoos** [comment]
😀😃😄😁😆😅🤣✌👍👍👍👍👍👍👏!

> Should I comment out or take them out?

Comment them out, with a note that they have been identified as not supported by browser

**Comment by RunaRagnarok** [comment]
Done for Windows.
Do we still need an extra Keyboard for Mac? Cant test on Mac :(

**Comment by berndmoos** [comment]
> Do we still need an extra Keyboard for Mac? Cant test on Mac :(

I think we do -- the MAC also needs to know about a suitable font. Can't test neither... If it doesn't work, it also does no harm.

**Comment by berndmoos** [comment]
Let's assume it is okay on the MAC and close this.

**Comment by RunaRagnarok** [comment]
The emojis are not shown in the tier, because the default tier font is not Segoe UI Emoji. Is there a way to insert the emojis per default with Segoe UI Emoji (Windows) or Apple Color Emoji (Mac)?

**Comment by berndmoos** [comment]
> Let's assume it is okay on the MAC and close this.

It is not okay on the MAC. Apple Color Emoji is not preinstalled on my MAC. After installing it, I still get blank boxes in the virtual keyboard. Remove it?

> Is there a way to insert the emojis per default with Segoe UI Emoji (Windows) or Apple Color Emoji (Mac)?

You can set the default tier font via "Edit > Preferences > Font..." Otherwise: no, there is no way of inserting specific characters in a specific font.

**Comment by berndmoos** [comment]
Let's close it
